### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by Sexniner** [TheKingFireS/TermuxDepotDownloader#1]
Is this thing safe??and how does it work steam cmd or what exactly is it use official steam client to download or what?

**Comment by TheKingFireS** [comment]
>Is this thing safe?
Yep, you can read my shell script here if you want.
>how does it work steam cmd or what exactly is it use official steam client to download or what?
That's question that you can ask on https://github.com/SteamRE/DepotDownloader.
This repo is just simple shell script to install DepotDownloader on Termux without having to copy-paste all command-lines.
