### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by unk0wn-u53r** [TheKingFireS/TermuxDepotDownloader#2]
Can we use also Manifest? I need this to download  a older version of my game, please 🙏🥹

Thank you for your hard work!

**Comment by TheKingFireS** [comment]
It's just official depotdownloader executable running on proot debian, of course you can.
If you don't know how to do it, you can read ``readme`` in [official repo](https://github.com/SteamRE/DepotDownloader/?tab=readme-ov-file#parameters).
