### ISSUE TITLE
I get this error when I want to download an app

### ISSUE THREAD

**Issue by ElixirXDE** [TheKingFireS/TermuxDepotDownloader#4]
"GC heap initialization failed with error 0x8007000E
Failed to create CoreCLR, HRESULT: 0x8007000E"

I want to download the hl mmod that is in my library but I get that error, I have arm64 I don't know if it's because of that, but it used to work very well

**Comment by ElixirXDE** [comment]
The link does not work

**Comment by TheKingFireS** [comment]
That's dotnet's problem. Exit proot, then run this command in Termux and try again. (I'm sure it was already added to shell script)
``echo "export DOTNET_GCHeapHardLimit=1C0000000" >> $PREFIX/var/lib/proot-distro/installed-rootfs/debian/etc/profile``
