### ISSUE TITLE
Error in Steam authorisation

### ISSUE THREAD

**Issue by Lumino-2-0** [TheKingFireS/TermuxDepotDownloader#5]
I succefully install the script and dependancies. But when the depotdownloader tried to connect to steam and install game, It show me an folder unauthorizated error. See my screenshots for the information. I was able to connect my account, I granted access of my Steam guard with the Steam app.

![Screenshot_20241016_225635](https://github.com/user-attachments/assets/77f19d95-eea0-4a87-972e-1cf052accc15)

Thanks for your support.
Sorry for my potential typo, my corrector IS in french.

**Comment by TheKingFireS** [comment]
I need more info, what's Android version, Termux version and command line? (please don't forget to censor your private info)

**Comment by Lumino-2-0** [comment]
I'm on Redmagic 9s pro, Android 14. It's when I executed the command ./DepotDownloader with the option (look like good configurated because he was able to connect to m'y Steam account). I used the F-Droid app to install my termux AND the termux from github source (arm64 version and Universal one). Same problem. Do you need more information ?

**Comment by TheKingFireS** [comment]
It's enough, thanks. I still try to help because I don't have my personal android 14 device. I'll open official android virtual device.

**Comment by Lumino-2-0** [comment]
Thanks you verry much ! I think i'm not be disponible until tomorrow to fix my issue. But thanks for your support.

**Comment by TheKingFireS** [comment]
I got same error, nice. I'll investigating it.

**Comment by TheKingFireS** [comment]
Seem like due to SteamKit (the library DD used) tried to read /sys/class/net to get MAC address, but they can't since Android restrict it. I'll temporarily downgrade DD version.

**Comment by Lumino-2-0** [comment]
Ok thanks for the update infos ! I understand.

**Comment by TheKingFireS** [comment]
DD 2.7.4 got released and it has this error fixed.
